on:
  push:
    branches:
    - main
jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-22.04
    steps:
    - name: Set up SSH
      env:
        SSH_KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        DEPLOYMENT_COMMAND: ${{ secrets.SSH_DEPLOYMENT_COMMAND }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/deployment.key
        chmod 600 ~/.ssh/deployment.key
        echo "$SSH_CONFIG" > ~/.ssh/config
    - name: Deploy application
      run: ssh deployment "$DEPLOYMENT_COMMAND"
